config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root "homes#top"
  get "home/about" => "homes#about"
  get "home/index" => "homes#index"
  resources :users, only: [:index, :show, :edit, :update, :create] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  resources :books, only: [:index, :show, :edit, :update, :destroy, :create] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user, optional: true
  
  validates :title, presence: true
  validates :body, length: { in:1..200 }
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}")
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :profile_image
  
  validates :name, length: { in: 2..20 }, uniqueness: { case_sensitive: false }
  validates :introduction, length: { maximum: 50 }
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
          has_many :books, dependent: :destroy
          has_many :favorites, dependent: :destroy
          has_many :book_comments, dependent: :destroy
          
          has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
          has_many :followers, through: :reverse_of_relationships, source: :follower
          has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
          has_many :followings, through: :relationships, source: :followed
          
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    book_comment = BookComment.new(book_comment_params)
    book_comment.book_id = @book.id
    book_comment.user_id = current_user.id
    book_comment.save
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to "/books/#{@book.id}"
    else
      @books = Book.all
      render :index
    end
  end
  
  def show
    @books = Book.find(params[:id])
    @book = Book.new
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == @book.user_id
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end
  
  def destroy
    @books = Book.find(params[:id])
    @books.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    fovorite = current_user.favorites.new(book_id: @book.id)
    fovorite.save
  end
  
  def destroy
     @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book =Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to "/books/#{@book.id}"
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book =Book.new
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless current_user.id == @user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<% book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user.id) do %>
        <%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <% if current_user == book_comment.user %>
      <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-sm btn-danger", method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$(".comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".comment").html("<%= j(render "book_comments/comment", book_comments: @book.book_comments) %>");
$(".inputComment").val("");

app/views/book_comments/destroy.js.erb
$(".comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".comment").html("<%= j(render "book_comments/comment", book_comments: @book.book_comments) %>");

app/views/books/_list.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: @book, local:true do |f| %>
  <div class="form-group">
    <p>Title</p>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <p>Opinion</p>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <p><%= f.submit 'Create Book' %></p>
  </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
          <% end %>
        <% end %>
        <h1>User info</h1>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <p>Title</p>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <p>Opinion</p>
          <%= f.text_field :body %>
        </div>
        <div class="form-group">
          <p><%= f.submit "Update Book" %></p>
        </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id)%> | <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
    <div class="container px-5 px-sm-0">
        <div class="row">
            <div class="col-md-3">
                <% if @book.errors.any? %>
                    <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
                    <% @book.errors.full_messages.each do |message| %>
                    <ul>
                      <li><%= message %></li>
                    </ul>
                    <% end %>
                <% end %>
                  <h2>User info</h2>
                   <%= attachment_image_tag current_user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
                   <table class="table">
                        <tbody>
                            <tr>
                              <th>name</th>
                              <th><%= current_user.name %></th>
                            </tr>
                            <tr>
                                <th>introduction</th>
                                <th><%= current_user.introduction %></th>
                            </tr>
                        </tbody>
                    </table>
                    <div class="row">
                        <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" do %>
                        <i class="fas fa-user-cog"></i>
                        <% end %>
                    </div>
                <%= render 'books/list', book: @book %>
                <div class="col-md-8 offset-md-1">
                    <h2>books</h2>
                    <table class="table table-hover table-inverse">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th>Opinion</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @books.each do |book| %>
                            <tr>
                                <td>
                                    <%= link_to user_path(book.user) do %>
                                    <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %>
                                    <% end %>
                                </td>
                                <td><%= link_to book.title, book_path(book) %></td>
                                <td><%= book.body %></td>
                                <td id="book_<%= book.id %>">
                                    <%= render "favorites/favorite", book: book %>
                                </td>
                                <td>
                                  コメント数:<%= book.book_comments.count %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
          <h2>User info</h2>
           <%= attachment_image_tag @books.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
           <table class="table">
                <tbody>
                    <tr>
                      <th>name</th>
                      <th><%= @books.user.name %></th>
                    </tr>
                    <tr>
                       <th>introduction</th>
                       <th><%= @books.user.introduction %></th>
                    </tr>
                </tbody>
            </table>
            <div class="row">
              <% if current_user.id == @books.user_id %>
                <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_6273" do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
              <% else %>
                <%= link_to edit_user_path(@books.user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_6273" do %>
                <i class="fas fa-user-cog"></i>
                <% end %>
              <% end %>
            </div>
      <%= render 'books/list', book: @book %>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
          <table class="table">
            <tbody>
              <tr>
                <td><%= attachment_image_tag @books.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%=link_to @books.user.name, user_path(@books.user_id) %>
                </td>
                <td><%=link_to @books.title, book_path(@books.id) %></td>
                <td><%= @books.body %></td>
                  <td id="book_<%= @books.id %>">
                      <%= render "favorites/favorite", book: @books %>
                  </td>
                <td class="comments-count">
                  コメント数:<%= @books.book_comments.count %>
                </td>
                <% if current_user.id == @books.user_id %>
                  <td><%= link_to "Edit", edit_book_path, class: "btn btn-sm btn-success" %></td>
                  <td><%= link_to "Destroy", book_path, class: "btn btn-sm btn-danger", method: :delete %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
          <table class="comment">
              <%= render "book_comments/comment", book_comments: @books.book_comments %>
          </table>
          <div class="new-comment">
            <%= form_with model: [@books,@book_comment] do |f| %>
              <div class="form-group">
                <%= f.text_area :comment, class: "inputComment" %>
              </div>
              <div class="form-group">
                <%= f.submit "送信" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>

        <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        ♥<%= book.favorites.count %>
        <% end %>

<% else %>

    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
    <% end %>

<% end %>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %>").html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %>").html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<table class="table">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td><%= link_to "Show", user_path(user) %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow User</h2>
<% if @users.exists? %>
<table class="table">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td><%= link_to "Show", user_path(user) %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/edit.html.erb
<main>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <% if @user.errors.any? %>
      <h3><%= @user.errors.count %>errors prohibited this book from being saved:</h3>
      <% @user.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></li>
      </ul>
      <% end %>
    <% end %>
    <h1>User info</h1>
    <%= form_with model:@user, local:true do |f| %>
      <p>Name</p>
      <%= f.text_field :name %>
      <p>Image</p>
      <%= f.attachment_field :profile_image %>
      <p>Introduction</p>
      <%= f.text_field :introduction %>
      <p><%= f.submit "Update User" %></p>
    <% end %>
  </div>
</main>

app/views/users/index.html.erb
<main>
    <div class="container px-5 px-sm-0">
        <div class="row">
            <div class="col-md-3">
                <h2>User info</h2>
                <%= attachment_image_tag current_user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
                <table class="table">
                    <tbody>
                        <tr>
                          <th>name</th>
                          <th><%= current_user.name %></th>
                        </tr>
                        <tr>
                            <th>introduction</th>
                            <th><%= current_user.introduction %></th>
                        </tr>
                    </tbody>
                </table>
                <div class="row">
                    <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_6273" do %>
                    <i class="fas fa-user-cog"></i>
                    <% end %>
                </div>
                <%= render 'books/list', book: @book %>
                <div class="col-md-8 offset-md-1">
                    <h2>Users</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>image</th>
                                <th>name</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @users.each do |user| %>
                            <tr>
                                <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
                                <td><%= user.name %></td>
                                <td>フォロー数:<%= user.followings.count %></td>
                                <td>フォロワー数:<%= user.followers.count %></td>
                                <td>
                                    <% if current_user != user %>
                                        <% if current_user.following?(user) %>
                                          <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
                                        <% else %>
                                          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                                        <% end %>
                                    <% end %>
                                </td>
                                <td><%= link_to "Show", user_path(user) %></td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>

app/views/users/show.html.erb
<main>
    <div class="container px-5 px-sm-0">
        <div class="row">
            <div class="col-md-3">
              <h2>User info</h2>
               <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
               <table class="table">
                    <tbody>
                        <tr>
                          <th>name</th>
                          <th><%= @user.name %></th>
                        </tr>
                        <tr>
                            <th>introduction</th>
                            <th><%= @user.introduction %></th>
                        </tr>
                        <tr>
                            <th>follows</th>
                            <th><%= link_to @user.followings.count, user_followings_path(@user.id) %></th>
                        </tr>
                        <tr>
                            <th>follower</th>
                            <th><%= link_to @user.followers.count, user_followers_path(@user.id) %></th>
                        </tr>
                    </tbody>
                </table>
                <div class="row">
                        <% if current_user.following?(@user) %>
                          <%= link_to "フォローを外す", user_relationships_path(@user.id), class: "btn btn-outline-secondary btn-block", method: :delete %>
                        <% else %>
                          <%= link_to "フォローする", user_relationships_path(@user.id), class: "btn btn-outline-secondary btn-block", method: :post %>
                        <% end %>
                </div>
                <%= render 'books/list', book: @book %>
                <div class="col-md-8 offset-md-1">
                        <h2>Books</h2>
                    <table class="table table-hover table-inverse">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th>Opinion</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @books.each do |book| %>
                            <tr>
                                <td>
                                    <%= link_to user_path(book.user) do %>
                                    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %>
                                    <% end %>
                                </td>
                                <td><%= link_to book.title, book_path(book) %></td>
                                <td><%= book.body %></td>
                                <td>
                                  コメント数:<%= book.book_comments.count %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>