config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root "homes#top"
  get "home/about" => "homes#about"
  get "home/index" => "homes#index"
  resources :users, only: [:index, :show, :edit, :update, :create] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  resources :books, only: [:index, :show, :edit, :update, :destroy, :create] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user, optional: true
  
  validates :title, presence: true
  validates :body, length: { in:1..200 }
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}")
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :profile_image
  
  validates :name, length: { in: 2..20 }, uniqueness: { case_sensitive: false }
  validates :introduction, length: { maximum: 50 }
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
          has_many :books, dependent: :destroy
          has_many :favorites, dependent: :destroy
          has_many :book_comments, dependent: :destroy
          
          has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
          has_many :followers, through: :reverse_of_relationships, source: :follower
          has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
          has_many :followings, through: :relationships, source: :followed
          
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to "/books/#{@book.id}"
    else
      @books = Book.all
      render :index
    end
  end
  
  def show
    @books = Book.find(params[:id])
    @book = Book.new
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == @book.user_id
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end
  
  def destroy
    @books = Book.find(params[:id])
    @books.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    fovorite = current_user.favorites.new(book_id: @book.id)
    fovorite.save
  end
  
  def destroy
     @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
  def index
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book =Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to "/books/#{@book.id}"
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book =Book.new
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless current_user.id == @user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "flash flash__#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
     
    <script src="jquery.min.js"></script>
    <script src="app.js"></script>
     
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path %>
          <% if user_signed_in? %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-link">
                    <i class="fas fa-home"></i>
                    <%= link_to "lesson", home_index_path %>
                  </li>
                  <li class="nav-link">
                    <i class="fas fa-home"></i>
                    <%= link_to "Home", user_path(current_user.id) %>
                  </li>
                  <li class="nav-link">
                    <i class="fas fa-users"></i>
                    <%= link_to "Users", users_path %>
                  </li>
                  <li class="nav-link">
                    <i class="fas fa-book-open"></i>
                    <%= link_to "Books", books_path %>
                  </li>
                  <li class="nav-link">
                    <i class="fas fa-sign-out-alt"></i>
                    <%= link_to "logout", destroy_user_session_path, method: :delete %>
                  </li>
              </ul>
          <% else %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-link">
                    <i class="fas fa-home"></i>
                    <%= link_to "lesson", home_index_path %>
                  </li>
                  <li class="nav-link">
                    <i class="fas fa-home"></i>
                    <%= link_to "Home", root_path %>
                  </li>
                  <li class="nav-link">
                    <i class="fas fa-link"></i>
                    <%= link_to "About", home_about_path %>
                  </li>
                  <li class="nav-link">
                    <i class="fas fa-user-plus"></i>
                    <%= link_to "sign up", new_user_registration_path %>
                  </li>
                  <li class="nav-link">
                    <i class="fas fa-sign-in-alt"></i>
                    <%= link_to "login", user_session_path %>
                  </li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <% if user_signed_in? %>
      <div class="search">
        <%= form_with url: search_path, method: :get, local: :true do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
          <%= f.select :search, options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
      <% end %>
    <%= render "layouts/flash" %>
    <%= yield %>
    
    <fotter>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </fotter>
  </body>
</html>